# Generated by Django 5.0.1 on 2024-01-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('rating', models.DecimalField(decimal_places=1, default=3.0, max_digits=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id_municipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.municipal')),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.state')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
        ),
    ]
