# Generated by Django 5.0.1 on 2024-01-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='id_municipal',
        ),
    ]
