# Generated by Django 5.0.1 on 2024-01-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_remove_place_id_municipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=45)),
                ('image', models.ImageField(upload_to='categroies/')),
            ],
        ),
    ]
