# Generated by Django 5.0.1 on 2024-01-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_remove_category_image_category_icon_and_more'),
        ('state', '0003_alter_state_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='place.place'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='place.category'),
        ),
        migrations.AlterField(
            model_name='place',
            name='id_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state', to='state.state'),
        ),
        migrations.AlterField(
            model_name='place',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
