# Generated by Django 5.0.1 on 2024-01-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Municipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipal_name', models.CharField(default='', max_length=45)),
                ('id_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.state')),
            ],
        ),
    ]
