# Generated by Django 5.0.1 on 2024-01-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_remove_place_id_municipal'),
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Municipal',
        ),
    ]
